// Mapping from provider names in registry to provider IDs in providers.json
export const providerNameToIdMap: Record<string, string> = {
  "Open edX / Axim Collaborative": "open-edx-axim",
  "Axim collaborative": "open-edx-axim",
  "Raccoon Gang": "raccoon-gang",
  "Overhang.io": "overhang-io",
  "Overhang.IO": "overhang-io",
  "OpenCraft": "opencraft",
  "edunext": "edunext",
  "eduNEXT": "edunext",
  "Appsembler": "appsembler",
  "edly": "edly",
  "hastexo": "hastexo",
  "MIT xPRO": "mitxpro",
  "MIT Office of distant learning": "mitxpro",
  "Stanford Online": "stanford-online",
  "Microsoft": "microsoft",
  "Google": "google",
  "IntelliBoard": "intelliboard",
  "Proversity": "proversity",
  "Triboo": "triboo",
  "HarvardX": "harvard",
  "openfun": "openfun",
  "Universidad de Chile": "universidad-chile",
  "Examus Inc": "examus",
  "Open learning initiative": "oli",
  "Jazkarta": "jazkarta",
  "IBL education": "ibl-education",
  "UBC - University of British Columbia": "ubc",
  "Abstract-Technology": "abstract-technology",
  "Centrica": "centrica",
  "OmniLearn": "omnilearn",
  "edX": "edx-inc",
  "Openedx.fr": "openedx-fr",
  "Edraak": "edraak",
  "Learner-course-dashboard": "learner-course-dashboard",
  "Arbisoft": "arbisoft",
  "Mcgraw-hill": "mcgraw-hill",
  "Openlearning": "openlearning",
  "Pearson": "pearson",
  "2U": "2u",
  "MITx": "mitx",
};

export function getProviderIdFromName(providerName: string): string {
  return providerNameToIdMap[providerName] || providerName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}