// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piafklhiggaucmblzgsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYWZrbGhpZ2dhdWNtYmx6Z3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjQ4MzAsImV4cCI6MjA2OTgwMDgzMH0.Lx8-R8uXMrBY0KBtMPgTNAOjZLFXZM0YE1DXAP5gJVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});